name: docker-push
on:
  workflow_call:
    secrets:
      gh-token:
        required: true
      gcp-sa-json:
        required: true
        description: GCP access key in Json that have permissions to push images to repo
      gcp-project-id:
        required: true
        description: GCP Project ID
      slack-build-webhook:
        required: false
    inputs:
      repository-base-name:
        required: true
        type: string
        description: Docker registry's repository name
      docker-registry:
        type: string
        description: Docker registry DNS
        default: europe-west1-docker.pkg.dev
      docker-tag:
        type: string
        description: Docker tag
        default: dev
      context:
        type: string
        description: Docker context, path to where find the dockerfile..
        default: .
      file:
        type: string
        description: Dockerfile name
        default: Dockerfile
    outputs:
      sha-short:
        value: ${{ jobs.docker-push.outputs.sha-short }}
        description: short SHA of the commit
      branch:
        value: ${{ jobs.docker-push.outputs.branch }}
        description: branch name

jobs:
  docker-push:
    runs-on: self-hosted
    outputs:
      sha-short: ${{ steps.vars-step.outputs.sha-short }}
      branch: ${{ steps.vars-step.outputs.branch }}
    steps:
      - name: Init git vars
        shell: bash
        id: vars-step
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ "${{ github.event_name }}" == "issue_comment" ]]; then
            export JSON_RESP=`curl -s --request GET --url "${{ github.event.issue.pull_request.url }}" --header "Authorization: Bearer ${{ env.GH_TOKEN}}"`
            echo "sha-short=`echo $JSON_RESP | jq -r .head.sha | cut -c1-7`" >> $GITHUB_OUTPUT
            echo "branch=`echo $JSON_RESP | jq -r .head.ref`" >> $GITHUB_OUTPUT
          elif [[ $GITHUB_REF = *refs/heads/* ]]; then
            echo "sha-short=`echo $GITHUB_SHA | cut -c1-7`" >> $GITHUB_OUTPUT
            echo "branch=$GITHUB_REF_NAME" >> $GITHUB_OUTPUT
          else
            echo "sha-short=`echo ${{ github.event.pull_request.head.sha }} | cut -c1-7`" >> $GITHUB_OUTPUT
            echo "branch=$GITHUB_HEAD_REF" >> $GITHUB_OUTPUT
          fi
      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.vars-step.outputs.branch }}

      - name: Login to GCR
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.docker-registry }}
          username: _json_key
          password: ${{ secrets.gcp-sa-json }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Detect Builder stage
        shell: bash
        id: builder-detect
        run: |
          if grep -q "as builder" ${{ inputs.context}}/${{ inputs.file }}; then
            echo "available=true" >> $GITHUB_OUTPUT;
          else
            echo "available=false" >> $GITHUB_OUTPUT;
          fi
      - name: Build builder 
        id: build-docker-builder-img
        if: ${{ steps.builder-detect.outputs.available == 'true' }}
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.context}}/${{ inputs.file }}
          push: true
          target: builder
          tags: |
            ${{ inputs.docker-registry}}/${{ secrets.gcp-project-id }}/cache/${{ inputs.repository-base-name }}:builder
          cache-from: |
            type=registry,ref=${{ inputs.docker-registry}}/${{ secrets.gcp-project-id }}/cache/${{ inputs.repository-base-name }}:builder
          cache-to: type=registry,ref=${{ inputs.docker-registry}}/${{ secrets.gcp-project-id }}/cache/${{ inputs.repository-base-name }}:builder,compression=zstd,mode=max
          build-args: |
            GH_ACCESS_TOKEN=${{ secrets.gh-token }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.gh-token }}
        env:
          DOCKER_BUILDKIT: 1
      - name: Build and Push image
        id: build-push-docker-img
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.context}}/${{ inputs.file }}
          push: true
          tags: |
            ${{ inputs.docker-registry}}/${{ secrets.gcp-project-id }}/solsten/${{ inputs.repository-base-name }}:${{ steps.vars-step.outputs.sha-short }}
            ${{ inputs.docker-registry}}/${{ secrets.gcp-project-id }}/solsten/${{ inputs.repository-base-name }}:${{ inputs.docker-tag }}
            ${{ inputs.docker-registry}}/${{ secrets.gcp-project-id }}/solsten/${{ inputs.repository-base-name }}:${{ steps.vars-step.outputs.branch }}
          cache-from: |
            type=registry,ref=${{ inputs.docker-registry}}/${{ secrets.gcp-project-id }}/cache/${{ inputs.repository-base-name }}
            type=registry,ref=${{ inputs.docker-registry}}/${{ secrets.gcp-project-id }}/cache/${{ inputs.repository-base-name }}:builder
          cache-to: type=registry,ref=${{ inputs.docker-registry}}/${{ secrets.gcp-project-id }}/cache/${{ inputs.repository-base-name }},compression=zstd,mode=max
          build-args: |
            GH_ACCESS_TOKEN=${{ secrets.gh-token }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.gh-token }}
        env:
          DOCKER_BUILDKIT: 1