name: github-release

on:
  workflow_call:
    secrets:
      gh-token:
        required: true
jobs:
  release:
    name: "Github Tag & Release"
    runs-on: "ubuntu-latest"

    steps:
      - run: |
          cd $GITHUB_WORKSPACE
          export SEMVER=`echo "${{ github.event.head_commit.message }}" | grep "release" | cut -d '-' -f 2 | head -n 1`
          echo "SEMVER=$SEMVER" >> $GITHUB_ENV
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.gh-token }}"
          automatic_release_tag: "${{ env.SEMVER }}"
          prerelease: false
          draft: false
          title: "Release ${{ env.SEMVER }}"
