name: go-build

on:
  workflow_call:
    secrets:
      gh-token:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:          
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-${{ github.repository }}-go
          restore-keys: |
            ${{ runner.os }}-${{ github.repository }}-go

      - name: Granting private modules access
        shell: bash
        env:
          ORG_GITHUB_TOKEN: ${{ secrets.gh-token }}
        run: |
            git config --global url."https://$ORG_GITHUB_TOKEN@github.com/12traits".insteadOf "https://github.com/12traits"   

      - name: Build
        shell: bash
        env:
          BUILD_NUMBER: ${{ github.run_number }}
        run: go build ./...

      - name: Test
        shell: bash
        run: go test -v ./... 

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:  
        - uses: actions/setup-go@v3
          with:
            go-version: 1.19

        - uses: actions/checkout@v3

        - name: Granting private modules access
          shell: bash
          env:
            ORG_GITHUB_TOKEN: ${{ secrets.gh-token }}
          run: |
              git config --global url."https://$ORG_GITHUB_TOKEN@github.com/12traits".insteadOf "https://github.com/12traits"           

        # run locally by installing golangci-lint https://golangci-lint.run/usage/install/#local-installation
        # and executing it in the root of the project
        - name: golangci-lint
          uses: golangci/golangci-lint-action@v3.2.0
          with:
            args: --timeout=5m --enable unparam
 
