name: go-build

on:
  workflow_call:
    secrets:
      gh-token:
        required: true
    inputs:
      workdir:
        type: string
        description: Directory where the go code can be found
        default: ./
      linter:
        type: string
        description: What type you prefer
        default: golangci
      path:
        type: string
        description: Path to look at from within the workdir
        default: ./pkg/... ./cmd/...
      go-version:
        type: string
        description: Golang version
        default: 1.22

jobs:
  test:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.workdir }}
    steps:          
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go-version }}
          cache: false

      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.gh-token }}
          
      - name: Granting private modules access
        env:
          ORG_GITHUB_TOKEN: ${{ secrets.gh-token }}
        run: |
          git config --global url."https://${ORG_GITHUB_TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Build
        id: go-build
        env:
          BUILD_NUMBER: ${{ github.run_number }}
          GOPROXY: https://proxy.golang.org,direct
          GOPRIVATE: github.com/12traits
        run: go build ./...

      - name: Test
        id: go-unit-tests
        run: go test -v ./...

  manual-lint:
    name: manual-lint
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.workdir }}
    steps:  
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go-version }}
          cache: false

      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.gh-token }}

      - name: Granting private modules access
        env:
          ORG_GITHUB_TOKEN: ${{ secrets.gh-token }}
        run: |
          git config --global url."https://${ORG_GITHUB_TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Install lint tools
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          go install mvdan.cc/unparam@latest

      - name: Download dependencies
        env:
          GOPRIVATE: github.com/12traits
        run: go mod download

      - name: Verify dependencies
        env:
          GOPRIVATE: github.com/12traits
        run: go mod verify

      - name: go vet
        env:
          GOPRIVATE: github.com/12traits
        run: go vet ${{ inputs.path }}

      - name: staticcheck
        env:
          GOPRIVATE: github.com/12traits
        run: staticcheck ${{ inputs.path }}

      - name: unparam
        env:
          GOPRIVATE: github.com/12traits
        run: unparam ${{ inputs.path }}

