name: go-build

on:
  workflow_call:
    secrets:
      gh-token:
        required: true
      slack-build-webhook:
        required: false
    inputs:
      workdir:
        type: string
        description: Directory where the go code can be found
        default: ./
      linter:
        type: string
        description: What type you prefer
        default: golangci
      path:
        type: string
        description: Path to look at from within the workdir
        default: ./pkg/... ./cmd/...

jobs:
  test:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.workdir }}
    steps:          
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache: false

      - uses: actions/checkout@v4
      - name: Granting private modules access
        env:
          ORG_GITHUB_TOKEN: ${{ secrets.gh-token }}
        run: |
            git config --global url."https://${{ env.ORG_GITHUB_TOKEN }}@github.com/12traits".insteadOf "https://github.com/12traits"   

      - name: Build
        id: go-build
        env:
          BUILD_NUMBER: ${{ github.run_number }}
          GOPROXY: https://proxy.golang.org,direct
        run: go build ./...

      - name: Test
        id: go-unit-tests
        run: go test -v ./...

      - uses: act10ns/slack@v2
        with: 
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          webhook-url: ${{ secrets.slack-build-webhook }}
          message: "Building / testing PR ({{ env.GITHUB_BASE_REF }}/{{ env.GITHUB_REF_NAME }})"
        if: failure()
  manual-lint:
    name: manual-lint
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.workdir }}
    steps:  
        - uses: actions/setup-go@v4
          with:
            go-version: '1.22'
            cache: false

        - uses: actions/checkout@v4
        - name: Granting private modules access
          env:
            ORG_GITHUB_TOKEN: ${{ secrets.gh-token }}
          run: |
              git config --global url."https://${{ env.ORG_GITHUB_TOKEN }}@github.com/12traits".insteadOf "https://github.com/12traits"           
        - name: install go ci deps
          run: |
            go install honnef.co/go/tools/cmd/staticcheck@2024.1
            go install mvdan.cc/unparam@latest
        - name: verify dependencies
          run: go mod verify
        - name: go vet
          run: go vet ${{ inputs.path }}
        - name: staticcheck
          run: staticcheck ${{ inputs.path }}
        - name: unparam
          run: unparam ${{ inputs.path }}
        - uses: act10ns/slack@v2
          with: 
            status: ${{ job.status }}
            steps: ${{ toJson(steps) }}
            webhook-url: ${{ secrets.slack-build-webhook }}
            message: "Linting PR ({{ env.GITHUB_BASE_REF }}/{{ env.GITHUB_REF_NAME }})"
          if: failure()