name: kubernetes-deploy

on:
  workflow_call:
    secrets:
      k8s-sa-json:
        required: true
        description: K8S access key in Json that have permissions to set image:tag to kubernetes deployments
      gcp-project-id:
        required: true
        description: GCP Project ID
      slack-build-webhook:
        required: false
    inputs:
      deployment-image:
        required: true
        type: string
        description: K8s deployment image
      docker-image:
        required: true
        type: string
        description: Deployment docker image to deploy
      docker-tag:
        required: true
        type: string
        description: Docker image tag to deploy
      docker-registry:
        type: string
        description: Docker registry DNS
        default: eu.gcr.io
      cluster:
        required: true
        type: string
        description: Cluster name 
      zone:
        type: string
        description: Cluster zone
        default: europe-west1-b
      namespace:
        required: true
        type: string
        description: K8s namespace where the deployment was made
jobs:
  deploy-image:
    name: "Update docker image/tag to a k8s deployment"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - id: gcp-auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.k8s-sa-json }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v0'
        with:
          install_components: 'gke-gcloud-auth-plugin'
      - name: "Connect to cluster"
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ inputs.cluster }}
          location: ${{ inputs.zone }}
          project_id: ${{ secrets.gcp-project-id }}
      - name: Deploy
        id: deploy-docker-image
        run: |-
          kubectl set image deployment ${{ inputs.deployment-image }} -n ${{ inputs.namespace }} ${{ inputs.deployment-image }}=${{ inputs.docker-registry }}/${{ secrets.gcp-project-id }}/${{ inputs.docker-image }}:${{ inputs.docker-tag }}
          kubectl rollout status deployment/${{ inputs.deployment-image }} -n ${{ inputs.namespace }}
      - uses: act10ns/slack@v1
        with: 
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          webhook-url: ${{ secrets.slack-build-webhook }}
        if: always()