name: licenses-sbom

on:
  workflow_call:
    secrets:
      gh-token:
        required: true
      k8s-key:
        required: false
    
jobs:
  sbom-and-licenses:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: anchore/sbom-action/download-syft@v0
      - uses: anchore/sbom-action@v0
        with:
          path: .
          artifact-name: sbom.spdx
          output-file: /tmp/sbom.spdx
      - name: Perform checks
        id: license-check
        uses: 12traits/license_approval@master
        with:
          gh-token: ${{ secrets.gh-token }}
      - run: echo ${{ steps.license-check.outputs.license_report_json }} | base64 -d > /tmp/licenses-report.json
      - uses: actions/upload-artifact@v3
        with:
          name: licenses-report
          path: /tmp/licenses-report.json
  upload:
    runs-on: self-hosted
    needs: sbom-and-licenses
    # if: ${{ github.base_ref == 'master' }}
    steps:
      - name: Check for Secret availability
        id: secret-check
        # perform secret check & put boolean result as an output
        shell: bash
        run: |
          SECRET='${{ secrets.k8s-key }}'
          if [[ $SECRET = "" ]]; then
            echo "available=false" >> $GITHUB_OUTPUT;
          else
            echo "available=true" >> $GITHUB_OUTPUT;
          fi
      - name: Init git vars
        if: ${{ steps.secret-check.outputs.available == 'true' }}
        shell: bash
        id: vars-step
        env:
          GH_TOKEN: ${{ secrets.gh-token }}
        run: |
          if [[ $GITHUB_REF = *refs/heads/* ]]; then
            echo "sha-short=`echo $GITHUB_SHA | cut -c1-7`" >> $GITHUB_OUTPUT
          else
            echo "sha-short=`echo ${{ github.event.pull_request.head.sha }} | cut -c1-7`" >> $GITHUB_OUTPUT
          fi
      - id: gcp-auth
        if: ${{ steps.secret-check.outputs.available == 'true' }}
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.k8s-key }}
      - name: Set up Cloud SDK
        if: ${{ steps.secret-check.outputs.available == 'true' }}
        uses: 'google-github-actions/setup-gcloud@v0'
      - uses: actions/download-artifact@v3
        if: ${{ steps.secret-check.outputs.available == 'true' }}
        with:
          name: licenses-report
          path: /tmp/${{ steps.vars-step.outputs.sha-short }}
      - uses: actions/download-artifact@v3
        if: ${{ steps.secret-check.outputs.available == 'true' }}
        with:
          name: sbom.spdx
          path: /tmp/${{ steps.vars-step.outputs.sha-short }}
      - name: Upload files to GCS
        if: ${{ steps.secret-check.outputs.available == 'true' }}
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: '/tmp/${{ steps.vars-step.outputs.sha-short }}/'
          destination: '12traits-ci/${{ github.event.repository.name }}'
          glob: '*'
