name: licenses-sbom

on:
  workflow_call:

jobs:
  licenses-sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: anchore/sbom-action/download-syft@v0
      - uses: anchore/sbom-action@v0
        with:
          path: ./