name: licenses-sbom

on:
  workflow_call:

jobs:
  licenses-sbom:
  runs-on: ubuntu-latest
  steps:
    - uses: anchore/sbom-action/download-syft
    - uses: anchore/sbom-action@v0
      with:
        path: ./