name: licenses-sbom

on:
  workflow_call:

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: anchore/sbom-action/download-syft@v0
      - uses: anchore/sbom-action@v0
        with:
          path: .
  licenses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Perform checks
        id: license-check
        uses: ralexander-phi/license_approval@master
        with:
          package_manager: ''